server:
  port: 8988
spring:
  application:
    name: service-miya
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka